# -*- coding: utf-8 -*-
"""Screenplay data for ព្រះអាទិត្យថ្មីរះលើផែនដីចាស់ (after the novel by សួន សុរិន្ទ, 1960-61;
story basis: the summary at khsearch.com/qna/19257). Dialogue is an original cinematic adaptation,
not a quotation of the novel.

Every item is either a dialogue line L(...) or a non-dialogue shot X(...).
  L(speaker, khmer, english, emo, act, cam=None, pose=None, move=None, sfx=None, tts=None, pause=0.25)
  X(kind, dur, desc, cam=..., sfx=[...], pose=..., move=...)
cam:  'wide' | 'two:A,B' | 'med:A' | 'mcu:A' | 'cu:A' | 'ots:A>B' | 'insert:<name>'
move: 'enter_left' | 'enter_right' | 'exit_left' | 'exit_right' | 'to:X,D' | 'near:NAME'
Every scene gives each cast member a start mark (x, depth, base pose, facing).
"""

def L(sp, kh, en, emo="", act="", cam=None, pose=None, move=None, sfx=None, tts=None, pause=0.25):
    return dict(type="line", sp=sp, kh=kh, en=en, emo=emo, act=act, cam=cam,
                pose=pose or {}, pause=pause, tts=tts or kh, move=move or {}, sfx=sfx or [])

def X(kind, dur, desc, cam="wide", sfx=None, pose=None, move=None):
    return dict(type="shot", kind=kind, dur=dur, desc=desc, cam=cam, sfx=sfx or [],
                pose=pose or {}, move=move or {})

CHARACTERS = {
    "narrator": dict(kh="អ្នកនិទាន", en="Narrator"),
    "sam":      dict(kh="សម", en="Sam"),
    "soy":      dict(kh="សយ", en="Soy"),
    "mey":      dict(kh="ម៉ី", en="Mey"),
    "mom":      dict(kh="មុំ", en="Mom"),
    "kimleang": dict(kh="អ្នកស្រីគឹមលៀង", en="Madam Kim Leang"),
    "tasan":    dict(kh="តាសាន", en="Ta San"),
    "sau":      dict(kh="សៅ", en="Sau"),
    "broker":   dict(kh="យាយចាស់", en="Old Woman"),
    "hok":      dict(kh="ថៅកែហុក", en="Boss Hok"),
    "police":   dict(kh="ប៉ូលីស", en="Policeman"),
    "police2":  dict(kh="ប៉ូលីស", en="Policeman"),
    "chhuoy":   dict(kh="ភូឈួយ", en="Phu Chhuoy"),
    "yaykan":   dict(kh="យាយកាន", en="Grandma Kan"),
    "worker":   dict(kh="កម្មករ", en="Worker"),
    "sengly":   dict(kh="ថៅកែសេងលី", en="Boss Seng Ly"),
    "sengan":   dict(kh="សេងអាន", en="Seng An"),
    "senghong": dict(kh="សេងហុង", en="Seng Hong"),
    "yeng":     dict(kh="លោកយ៉េង", en="Mr. Yeng"),
    "nara":     dict(kh="គ្រូពេទ្យនរា", en="Doctor Nara"),
    "oknha":    dict(kh="លោកឧកញ៉ា", en="The Oknha"),
    "minister": dict(kh="លោករដ្ឋមន្ត្រី", en="The Minister"),
    "huor":     dict(kh="ហួរ", en="Huor"),
    "suos":     dict(kh="សួស", en="Suos"),
    "worker2":  dict(kh="កម្មករ", en="Worker"),
    "worker3":  dict(kh="កម្មករ", en="Worker"),
    "guard":    dict(kh="ឆ្មាំ", en="Guard"),
}

SCENES = [
# ═════════════════════════════════════════════════════════ CHAPTER 1 — FROM THE COUNTRYSIDE
dict(n=1, ch=1, title_kh="ពីជនបទ", title_en="From the Countryside", source="សង្ខេបរឿង ¶1",
     music="opening", amb="country", loc="village", tod="dawn",
     cast=["sam", "soy"],
     start=dict(sam=(-60, 0.15, "hoe", 1), soy=(700, 0.1, "stand", -1)),
     items=[
  X("establish", 8.0, "Sunrise over dry rice fields and sugar-palm trees. Birds. A small wooden house on stilts.",
    cam="insert:village_sunrise", sfx=["birds_morning"]),
  L("narrator", "ចុងទសវត្សរ៍ ១៩៥០។ នៅភូមិតូចមួយ មានយុវកសិករម្នាក់ឈ្មោះ សម។",
    "The late 1950s. In a small village lived a young farmer named Sam.", "calm", "", cam="insert:village_sunrise",
    tts="ចុងទសវត្សរ៍ឆ្នាំមួយពាន់ប្រាំបួនរយហាសិប។ នៅភូមិតូចមួយ មានយុវកសិករម្នាក់ឈ្មោះ សម។"),
  L("narrator", "សម កំព្រាឪពុកម្ដាយតាំងពីតូច។ ប្រពន្ធរបស់គាត់ឈ្មោះ សយ ក៏កំព្រាដូចគ្នា។",
    "Sam lost his parents as a small child. His wife, Soy, was an orphan too.", "calm", "", cam="wide"),
  X("action", 4.5, "Sam hoes the hard, cracked field. Soy walks along the dyke carrying a clay water jar.",
    cam="wide", sfx=["hoe_dirt", "footsteps_dirt"], move={"soy": "to:120,0.12"}),
  L("soy", "បងសម សម្រាកផឹកទឹកសិនទៅ។", "Sam, rest and drink some water.", "gentle", "holds out the jar",
    cam="med:soy", pose={"soy": "offer"}),
  L("sam", "ដីឆ្នាំនេះរឹងណាស់ សយ។ ភ្លៀងមិនធ្លាក់សោះ។", "The soil is so hard this year, Soy. No rain at all.",
    "tired", "straightens up, wipes his brow", cam="med:sam", pose={"sam": "stand"}),
  L("soy", "ស្រូវយើងសល់តិចណាស់ហើយ... មិនដល់ខែក្រោយផង។", "We have so little rice left... not even enough for next month.",
    "worried", "", cam="two:sam,soy"),
  L("sam", "ដីនេះ ក៏មិនមែនជារបស់យើងដែរ។ ធ្វើប៉ុណ្ណា ក៏ត្រូវចែកឲ្យម្ចាស់ដីស្ទើរអស់។",
    "And this land isn't even ours. However hard we work, most of it goes to the landowner.", "bitter", "",
    cam="mcu:sam"),
  L("sam", "គេថា នៅភ្នំពេញ មានការងារច្រើន។ ធាក់ស៊ីក្លូ ក៏បានលុយរាល់ថ្ងៃដែរ។",
    "People say there's plenty of work in Phnom Penh. Even pedalling a cyclo brings money every day.",
    "hopeful", "looks toward the horizon", cam="mcu:sam"),
  L("soy", "ទីក្រុងធំ... យើងមិនស្គាល់នរណាសោះ បង។", "A big city... we don't know anyone there.", "uneasy", "",
    cam="mcu:soy"),
  L("sam", "មិនអីទេសយ... បើយើងនៅតែខំ យើងនឹងរកផ្លូវឃើញ។", "It's all right, Soy... if we keep trying, we'll find a way.",
    "tired but determined", "takes her hand", cam="two:sam,soy", pose={"sam": "hand_chest"}),
  L("soy", "បើបងទៅ អូនក៏ទៅដែរ។ យើងនៅជាមួយគ្នា។", "If you go, I go too. We stay together.", "gentle, loyal",
    "smiles softly", cam="mcu:soy", pause=0.6),
  X("establish", 6.0, "A steam train crosses the countryside at morning. Sam and Soy sit at an open window with one small cloth bundle.",
    cam="insert:train", sfx=["train_run"]),
  L("narrator", "គេទាំងពីរ ចាកចេញពីស្រុកកំណើត ដោយយកតែក្ដីសង្ឃឹមមួយ ទៅជាមួយ។",
    "The two of them left their home village, taking nothing with them but hope.", "calm", "",
    cam="insert:train", pause=0.8),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 2 — CYCLO LIFE
dict(n=2, ch=2, title_kh="ជីវិតអ្នកធាក់ស៊ីក្លូ", title_en="Cyclo Life in Phnom Penh", source="សង្ខេបរឿង ¶1",
     music="city", amb="street", loc="street", tod="day",
     cast=["sam", "police"],
     start=dict(sam=(-900, 0.2, "cyclo", 1), police=(420, 0.35, "stand", -1)),
     items=[
  X("establish", 6.0, "Busy Phnom Penh, late 1950s: shophouses with shutters, cyclos, bicycles, an old sedan, palm trees.",
    cam="insert:city_street", sfx=["cyclo_bell", "traffic_old"]),
  L("narrator", "នៅភ្នំពេញ សមជួលស៊ីក្លូរបស់អ្នកស្រីគឹមលៀង មកធាក់រកស៊ីរាល់ថ្ងៃ។",
    "In Phnom Penh, Sam rented a cyclo from Madam Kim Leang and pedalled it every day.", "calm", "",
    cam="insert:city_street"),
  X("action", 5.0, "Sam pedals an empty cyclo along the street, sweating in the heat.", cam="wide",
    sfx=["cyclo_bell", "cyclo_chain"], move={"sam": "to:-200,0.2"}),
  L("sam", "ថ្ងៃនេះបានតែបីរៀល... ដកថ្លៃជួលស៊ីក្លូ នៅសល់មិនប៉ុន្មានទេ។",
    "Only three riels today... after the cyclo rent, there's almost nothing left.", "tired", "counts coins",
    cam="med:sam"),
  L("sam", "ផ្លូវនេះកាត់ជិតជាង... ប្រញាប់បន្តិច ទាន់ទទួលភ្ញៀវនៅផ្សារ។",
    "This street is a shortcut... if I hurry I'll catch a fare at the market.", "hurried", "", cam="mcu:sam"),
  X("action", 3.5, "Sam turns into the street the wrong way. A whistle shrills. A traffic policeman steps out, arm raised.",
    cam="wide", sfx=["police_whistle", "cyclo_chain"], move={"sam": "to:250,0.2"}, pose={"police": "stop_hand"}),
  L("police", "ឈប់! ឯងធាក់បញ្ច្រាសទិសហើយ! មិនឃើញសញ្ញាផ្លូវទេឬ?",
    "Stop! You're riding against the traffic! Didn't you see the sign?", "stern", "", cam="med:police",
    pose={"police": "point"}),
  L("sam", "សុំទោសលោក... ខ្ញុំទើបមកពីស្រុក មិនទាន់ស្គាល់ផ្លូវច្បាស់ទេ។",
    "Sorry, sir... I've just come from the countryside. I don't know the streets well yet.", "nervous", "",
    cam="mcu:sam", pose={"sam": "cyclo_sampeah"}),
  L("police", "ច្បាប់គឺច្បាប់។ ត្រូវបង់ពិន័យ។ បើគ្មានលុយ ស៊ីក្លូនេះត្រូវទុកនៅប៉ុស្តិ៍។",
    "The law is the law. You must pay a fine. With no money, this cyclo stays at the police post.", "official", "",
    cam="ots:sam>police"),
  X("insert", 3.5, "Close-up: Sam's calloused hands hold a small printed fine slip (no readable text) beside a few coins.",
    cam="insert:fine_slip", sfx=["paper_page"]),
  L("sam", "លុយប៉ុណ្ណឹង... ខ្ញុំទៅរកឯណាមក?", "That much money... where would I ever find it?", "worried",
    "slowly lowers his eyes; slow push-in", cam="cu:sam", pause=0.6),
]),
dict(n=3, ch=3, title_kh="បាត់ស៊ីក្លូ", title_en="Losing the Cyclo", source="សង្ខេបរឿង ¶1",
     music="hardship", amb="street", loc="yard", tod="day",
     cast=["sam", "kimleang"],
     start=dict(sam=(-240, 0.1, "stand", 1), kimleang=(160, 0.1, "stand", -1)),
     items=[
  X("establish", 3.0, "Madam Kim Leang's cyclo yard: a row of cyclos under a tin roof. She waits, arms crossed.",
    cam="wide", pose={"kimleang": "arms_crossed"}),
  L("kimleang", "សម! ស៊ីក្លូខ្ញុំនៅឯណា? ឮថាប៉ូលីសផាកហើយ មែនទេ?",
    "Sam! Where is my cyclo? I heard the police impounded it, is that right?", "angry", "", cam="med:kimleang",
    pose={"kimleang": "arms_crossed"}),
  L("sam", "បាទអ្នកស្រី... ខ្ញុំរកលុយបង់ពិន័យមិនទាន់បាន។ សូមពន្យារពេលឲ្យខ្ញុំបន្តិចសិន។",
    "Yes, madam... I haven't found the money for the fine yet. Please give me a little more time.", "pleading", "",
    cam="mcu:sam", pose={"sam": "sampeah"}),
  L("kimleang", "ខ្ញុំជួលស៊ីក្លូ ដើម្បីរកស៊ី មិនមែនដើម្បីខាតបង់ទេ។",
    "I rent out cyclos to make a living, not to lose money.", "firm, cold", "", cam="mcu:kimleang"),
  L("kimleang", "ខ្ញុំនឹងទៅដោះស៊ីក្លូខ្លួនឯង។ ចាប់ពីថ្ងៃនេះ ឯងឈប់ធាក់ស៊ីក្លូខ្ញុំទៀតហើយ។",
    "I'll get the cyclo back myself. From today on, you don't ride my cyclos any more.", "stern", "",
    cam="ots:sam>kimleang", pose={"kimleang": "point"}),
  L("sam", "អ្នកស្រី... បើគ្មានស៊ីក្លូ ខ្ញុំនិងប្រពន្ធ យកអ្វីហូប?",
    "Madam... without a cyclo, how will my wife and I eat?", "desperate", "", cam="mcu:sam"),
  L("kimleang", "នោះជារឿងរបស់ឯង។", "That's your problem.", "dismissive", "turns away", cam="med:kimleang",
    move={"kimleang": "exit_right"}, pause=0.4),
  X("reaction", 3.5, "Sam stands alone in the yard among the parked cyclos, empty-handed.", cam="wide",
    pose={"sam": "head_down"}),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 3 — LOSING HOME
dict(n=4, ch=3, title_kh="បាត់ជម្រក", title_en="Losing Home", source="សង្ខេបរឿង ¶1",
     music="hardship", amb="rain_in", loc="hut", tod="dusk_rain",
     cast=["sam", "soy", "tasan"],
     start=dict(sam=(-120, 0.1, "sit", 1), soy=(60, 0.12, "sit", -1), tasan=(900, 0.1, "stand", -1)),
     items=[
  X("establish", 4.0, "Dusk, rain. A tiny rented hut of palm-leaf walls. An oil lamp. Water drips into a pot.",
    cam="wide", sfx=["thunder_far", "drip"]),
  X("action", 2.5, "Old Ta San pushes the door open and steps in out of the rain.", cam="wide",
    sfx=["door_wood"], move={"tasan": "to:330,0.1"}),
  L("tasan", "សម! ឯងជំពាក់ថ្លៃខ្ទមខ្ញុំពីរខែហើយ។", "Sam! You owe me two months' rent for this hut.", "stern",
    "", cam="med:tasan"),
  L("soy", "តា... សូមអាណិតយើងបន្តិចផង។ ប្ដីខ្ញុំទើបតែបាត់ការងារ។",
    "Grandpa... please take pity on us. My husband has just lost his work.", "pleading", "", cam="mcu:soy",
    pose={"soy": "sampeah"}),
  L("tasan", "ខ្ញុំក៏ក្រដែរ។ ខ្ទមនេះ ខ្ញុំត្រូវឲ្យគេជួលវិញ។ ព្រឹកស្អែក ចេញទៅ!",
    "I'm poor too. I have to rent this hut to someone else. Tomorrow morning, you leave!", "harsh", "",
    cam="med:tasan", pose={"tasan": "point"}),
  X("action", 2.5, "Ta San leaves. The door bangs in the wind. Sam drops his head into his hands.", cam="wide",
    sfx=["door_wood", "rain_heavy"], move={"tasan": "exit_right"}, pose={"sam": "sit_sad"}),
  L("sam", "បងជាប្ដីដែលគ្មានប្រយោជន៍... សូម្បីតែដំបូលមួយ ក៏រកឲ្យអូនមិនបាន។",
    "I'm a useless husband... I can't even keep a roof over your head.", "ashamed", "", cam="mcu:sam"),
  L("soy", "កុំនិយាយអញ្ចឹងបង។ យើងធ្លាប់ក្រជាងនេះ ក៏យើងនៅរស់ដែរ។",
    "Don't say that. We've been poorer than this, and we survived.", "gentle", "", cam="two:sam,soy"),
  L("soy", "ដរាបណាយើងនៅជាមួយគ្នា អូនមិនខ្លាចទេ។", "As long as we're together, I'm not afraid.", "hopeful",
    "puts a hand on his shoulder", cam="mcu:soy", pose={"soy": "hand_chest"}),
  X("action", 4.0, "By lamplight Soy ties their few clothes into two small bundles. Rain on the roof.", cam="wide",
    sfx=["cloth_rustle", "rain_heavy"], pose={"soy": "sit_work"}),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 4 — THE TEMPTATION
dict(n=5, ch=4, title_kh="ការល្បួង", title_en="The Temptation", source="សង្ខេបរឿង ¶2",
     music="threat", amb="night", loc="hut", tod="night",
     cast=["sam", "soy", "sau"],
     start=dict(sam=(-60, 0.1, "stand", 1), soy=(-360, 0.35, "sit_sad", 1), sau=(900, 0.1, "stand", -1)),
     items=[
  X("action", 3.0, "Night. The rain has stopped. Sau appears in the doorway, leaning on the frame.", cam="wide",
    sfx=["footsteps_wood", "crickets"], move={"sau": "to:250,0.1"}),
  L("sau", "សម... ឮថាឯងបាត់ស៊ីក្លូ ហើយត្រូវគេបណ្ដេញចេញពីខ្ទមទៀត។",
    "Sam... I hear you lost the cyclo, and now they're throwing you out of the hut too.", "sly", "",
    cam="med:sau"),
  L("sam", "មានការអ្វី បងសៅ?", "What do you want, Sau?", "wary", "", cam="mcu:sam"),
  L("sau", "ចូលដៃជាមួយក្រុមខ្ញុំទៅ។ មួយយប់ បានលុយច្រើនជាងធាក់ស៊ីក្លូមួយខែ។",
    "Join my group. One night brings more money than a month on a cyclo.", "manipulative", "",
    cam="ots:sam>sau"),
  L("sam", "លុយនោះ ជាលុយលួចឆក់គេ មែនទេ?", "That's money snatched from other people, isn't it?", "serious", "",
    cam="mcu:sam"),
  L("sau", "ធ្វើការសុចរិតប៉ុណ្ណេះ តើបានអ្វីមកវិញ? ក្រដដែល ឃ្លានដដែល។",
    "All this honest work — what has it got you? Still poor, still hungry.", "cynical", "spreads his hands",
    cam="med:sau", pose={"sau": "gesture_sit"}),
  X("reaction", 3.0, "Sam glances back at Soy, sitting worn out by the lamp. He breathes in.", cam="mcu:sam",
    sfx=["crickets"]),
  L("sam", "ខ្ញុំក្រមែន... តែខ្ញុំមិនចង់រស់លើទ្រព្យអ្នកដទៃទេ។",
    "I am poor... but I will not live off what belongs to others.", "firm", "slow push-in", cam="cu:sam"),
  L("sau", "ចាំមើលចុះ។ ពេលពោះឯងឃ្លានខ្លាំង ឯងនឹងនឹកដល់ពាក្យខ្ញុំ។",
    "We'll see. When your belly is really empty, you'll remember my words.", "cold", "", cam="med:sau",
    move={"sau": "exit_right"}),
  L("soy", "បងធ្វើត្រូវហើយ។", "You did the right thing.", "gentle, proud", "", cam="med:soy",
    move={"soy": "to:-230,0.12"}, pose={"soy": "stand"}),
  L("sam", "ស្អែក យើងទៅសុំស្នាក់នៅក្រោមសំយ៉ាបវិហារវត្តសិន។",
    "Tomorrow we'll ask to stay under the temple eaves for a while.", "determined", "", cam="two:sam,soy",
    pause=0.6),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 5 — SOY GOES TO WORK
dict(n=6, ch=5, title_kh="ក្រោមសំយ៉ាបវិហារ", title_en="Under the Temple Eaves", source="សង្ខេបរឿង ¶2-3",
     music="temple", amb="temple", loc="temple", tod="day",
     cast=["sam", "soy", "broker"],
     start=dict(sam=(-560, 0.1, "stand", 1), soy=(-120, 0.12, "sit_work", 1), broker=(900, 0.1, "stand", -1)),
     items=[
  X("establish", 5.5, "A Buddhist temple: a tiered roof with golden finials, a bodhi tree. Under the side eaves, Sam and Soy's two bundles on a mat.",
    cam="insert:temple_ext", sfx=["temple_bell", "birds_morning"]),
  L("narrator", "សម និងសយ បានមកស្នាក់នៅក្រោមសំយ៉ាបវិហារ នៃវត្តមួយ។ រាល់ថ្ងៃ សមដើររកការងារ... តែរកមិនបាន។",
    "Sam and Soy came to stay under the eaves of a temple hall. Every day Sam walked the city looking for work... and found none.",
    "calm", "", cam="insert:temple_ext"),
  X("action", 3.5, "Sam comes back along the temple wall, exhausted, and sits beside Soy.", cam="wide",
    sfx=["footsteps_sandal"], move={"sam": "to:-260,0.1"}, pose={"sam": "sit_sad"}),
  X("action", 2.5, "A talkative old woman with a betel basket approaches from the gate.", cam="wide",
    sfx=["footsteps_sandal"], move={"broker": "to:170,0.1"}),
  L("broker", "ក្មួយស្រី ឮថាក្មួយកំពុងរកការងារ។ ផ្ទះថៅកែហុក គេត្រូវការអ្នកបម្រើផ្ទះម្នាក់។",
    "Niece, I hear you're looking for work. Boss Hok's household needs a housemaid.", "kind", "",
    cam="med:broker"),
  L("soy", "ពិតមែនឬយាយ? ខ្ញុំចេះបោកខោអាវ ចម្អិនម្ហូប ធ្វើការផ្ទះបានទាំងអស់។",
    "Really, grandma? I can wash clothes, cook, do all the housework.", "hopeful", "", cam="mcu:soy",
    pose={"soy": "stand"}),
  L("sam", "សយ... អូនមិនដែលនៅឆ្ងាយពីបងទេ។ បងបារម្ភណាស់។",
    "Soy... you've never lived apart from me. I'm very worried.", "worried", "", cam="mcu:sam",
    pose={"sam": "stand"}),
  L("soy", "យើងត្រូវការលុយណាស់បង។ ដល់ពេលមានលុយ យើងនឹងជួលផ្ទះតូចមួយនៅជាមួយគ្នា។",
    "We need the money so badly. Once we have some, we'll rent a little house together.", "earnest", "",
    cam="two:sam,soy"),
  L("sam", "បើអញ្ចឹង... ទៅចុះ។ តែថែខ្លួនឲ្យបានល្អ ណាអូន។",
    "Then... go. But take good care of yourself.", "tender", "", cam="mcu:sam", pose={"sam": "hand_chest"}),
  X("action", 4.0, "Soy follows the old woman out through the temple gate, looking back once. Sam watches.",
    cam="wide", move={"soy": "exit_right", "broker": "exit_right"}, sfx=["temple_bell"]),
]),
dict(n=7, ch=5, title_kh="ផ្ទះថៅកែហុក", title_en="Boss Hok's House", source="សង្ខេបរឿង ¶3",
     music="threat", amb="house", loc="villa", tod="day",
     cast=["hok", "soy"],
     start=dict(hok=(160, 0.1, "stand", -1), soy=(-200, 0.12, "stand", 1)),
     items=[
  X("establish", 4.5, "A large colonial-style villa behind an iron gate: shutters, a veranda, potted palms.",
    cam="insert:villa_ext", sfx=["birds_city"]),
  L("hok", "ឯងឈ្មោះសយ មែនទេ? ធ្វើការឲ្យស្អាត ហើយស្ដាប់បង្គាប់ ខ្ញុំនឹងមិនធ្វើឲ្យឯងខាតទេ។",
    "Your name is Soy? Work neatly and do as you're told, and you won't regret it.", "controlled", "",
    cam="med:hok"),
  L("soy", "ចាស ថៅកែ។ ខ្ញុំនឹងខំធ្វើការ។", "Yes, boss. I'll work hard.", "polite, nervous", "", cam="mcu:soy",
    pose={"soy": "sampeah"}),
  X("action", 3.5, "Montage: Soy sweeps the long tiled floor.", cam="wide", sfx=["broom"],
    move={"hok": "exit_right"}, pose={"soy": "sweep"}),
  X("action", 3.0, "Montage: Soy scrubs a pot, working carefully.", cam="med:soy", sfx=["dish_wash"],
    pose={"soy": "work"}),
  X("establish", 4.0, "Night. Heavy rain lashes the villa. A wall clock shows nine o'clock.", cam="insert:villa_rain",
    sfx=["rain_heavy", "thunder_far", "clock_tick"]),
  X("action", 3.5, "Inside, late. Soy is drying a cup alone. Slow footsteps behind her. She turns, frightened.",
    cam="mcu:soy", sfx=["footsteps_wood"], pose={"soy": "hold_cup"}),
  X("insert", 2.0, "The cup slips from her hand and breaks on the tiles.", cam="insert:cup_drop",
    sfx=["cup_break"]),
  X("insert", 4.0, "A closed door in the dark corridor. Rain streams down the window. Fade to black.",
    cam="insert:closed_door", sfx=["rain_heavy"]),
  X("insert", 3.0, "Black. Only the rain.", cam="insert:black", sfx=["rain_heavy"]),
  X("establish", 4.0, "Grey morning. Soy walks out of the villa gate alone, her krama held tight around her shoulders.",
    cam="insert:morning_gate", sfx=["footsteps_sandal", "birds_city"]),
  L("narrator", "ព្រឹកឡើង សយបានចាកចេញពីផ្ទះនោះ ទាំងឈឺចាប់ក្នុងចិត្ត ទៅរកមិត្តរបស់ប្ដី គឺម៉ី និងមុំ។",
    "In the morning, Soy left that house, hurting deep inside, and went to her husband's friends, Mey and Mom.",
    "grave", "", cam="insert:morning_gate", pause=0.6),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 6 — SAM'S ANGER
dict(n=8, ch=6, title_kh="កំហឹងរបស់សម", title_en="Sam's Anger", source="សង្ខេបរឿង ¶3",
     music="hardship", amb="house_poor", loc="meyhome", tod="day",
     cast=["mey", "mom", "soy", "sam"],
     start=dict(mom=(-60, 0.1, "stand", 1), mey=(-330, 0.2, "stand", 1), soy=(-900, 0.1, "stand", 1),
                sam=(-900, 0.1, "stand", 1)),
     items=[
  X("action", 3.5, "A small wooden house by a pedicab stand. Soy stumbles in; Mom runs to her.", cam="wide",
    sfx=["footsteps_wood"], move={"soy": "to:-200,0.1"}),
  L("mom", "សយ! ម៉េចមកតែម្នាក់ឯង? មុខស្លេកស្លាំងម្ល៉េះ?", "Soy! Why have you come alone? You're so pale!",
    "worried", "", cam="med:mom"),
  L("soy", "បងមុំ... ខ្ញុំមិនអាចនៅផ្ទះនោះទៀតបានទេ។", "Mom... I can't stay in that house any more.",
    "distressed", "", cam="mcu:soy", pose={"soy": "hands_face"}),
  L("mey", "សយអង្គុយសិនទៅ។ ខ្ញុំទៅហៅសមមកឥឡូវ។", "Sit down, Soy. I'll go and fetch Sam right now.",
    "protective", "", cam="med:mey", move={"mey": "exit_left"}),
  X("action", 3.0, "Later. Sam rushes in with Mey, out of breath.", cam="wide", sfx=["footsteps_wood"],
    move={"sam": "to:-420,0.1", "mey": "to:-650,0.2"}, pose={"soy": "sit_sad"}),
  L("sam", "សយ! មានរឿងអ្វី? ប្រាប់បងមក!", "Soy! What happened? Tell me!", "urgent", "", cam="med:sam",
    move={"sam": "to:-330,0.1"}),
  L("soy", "យប់មិញ... ពេលភ្លៀងធ្លាក់ខ្លាំង... ថៅកែហុក... គាត់បានធ្វើបាបអូន។",
    "Last night... when the rain was heavy... Boss Hok... he abused me.", "cry", "", cam="mcu:soy",
    pose={"soy": "sit_sad"}),
  L("soy", "អូនខំតស៊ូហើយ បង... តែអូនមិនអាចគេចរួចទេ។", "I fought him... but I couldn't get away.", "cry", "",
    cam="cu:soy"),
  X("reaction", 3.0, "Sam freezes. His hands close into fists. Silence.", cam="cu:sam", sfx=["heartbeat_soft"],
    pose={"sam": "fists"}),
  L("sam", "វាហ៊ានធ្វើបាបប្រពន្ធខ្ញុំ... ខ្ញុំនឹងសម្លាប់វា!", "He dared to hurt my wife... I'll kill him!",
    "furious", "", cam="mcu:sam", pose={"sam": "fists"}),
  L("mom", "សម! ស្ងប់ចិត្តសិន! សយត្រូវការឯងនៅក្បែរ មិនមែនឲ្យឯងទៅជាប់គុកទេ!",
    "Sam! Calm down! Soy needs you by her side, not in prison!", "pleading", "", cam="med:mom",
    pose={"mom": "stop_hand"}),
  L("mey", "វាជាអ្នកមាន មានអំណាច។ ឯងទៅរកវាម្នាក់ឯង ឯងចាញ់ហើយ។",
    "He's rich and powerful. Go after him alone and you've already lost.", "warning", "", cam="med:mey",
    move={"mey": "to:-520,0.12"}),
  L("sam", "ចុះបើអ្នកមានធ្វើខុស ត្រូវឲ្យយើងអ្នកក្រនៅស្ងៀមឬ?",
    "So when the rich do wrong, we poor people must just keep quiet?", "angry", "", cam="ots:mey>sam"),
  L("soy", "បង... កុំទៅអី។ អូនបាត់បង់ច្រើនហើយ... អូនមិនចង់បាត់បង់បងទៀតទេ។",
    "Please... don't go. I've lost so much already... I can't lose you too.", "cry", "", cam="mcu:soy"),
  X("action", 3.0, "Mey holds Sam's shoulder. Sam turns away, breathing hard, and sits beside Soy.", cam="wide",
    pose={"sam": "sit_sad"}),
  L("narrator", "ទោះប្រពន្ធ និងមិត្តភក្ដិ ឃាត់យ៉ាងណាក៏ដោយ កំហឹងនៅតែឆេះក្នុងចិត្តសម។",
    "However much his wife and friends tried to hold him back, anger kept burning in Sam's heart.", "grave",
    "", cam="wide", pause=0.6),
]),
dict(n=9, ch=6, title_kh="ចាញ់កល", title_en="Outwitted", source="សង្ខេបរឿង ¶3",
     music="confront", amb="night", loc="villa", tod="night",
     cast=["sam", "hok", "police", "police2"],
     start=dict(hok=(260, 0.1, "stand", -1), sam=(-900, 0.1, "stand", 1), police=(-1000, 0.12, "stand", 1),
                police2=(-1080, 0.2, "stand", 1)),
     items=[
  X("establish", 4.0, "Night. Sam walks along the villa wall under a street lamp, jaw set.", cam="insert:night_gate",
    sfx=["footsteps_concrete", "crickets"]),
  X("action", 2.5, "Sam bursts into the lamplit hall. Hok turns from a cabinet.", cam="wide",
    sfx=["door_wood"], move={"sam": "to:-150,0.1"}),
  L("sam", "ហុក! ឯងធ្វើបាបប្រពន្ធខ្ញុំ! ថ្ងៃនេះ ឯងត្រូវតែទទួលខុសត្រូវ!",
    "Hok! You abused my wife! Tonight you will answer for it!", "furious", "", cam="med:sam",
    pose={"sam": "point"}),
  L("hok", "ស្ងប់ចិត្តសិន... យើងនិយាយគ្នាបាន។ ឯងចង់បានលុយប៉ុន្មាន?",
    "Calm down... we can talk. How much money do you want?", "controlled, evasive", "hand slides toward the bell",
    cam="med:hok", pose={"hok": "gesture_sit"}),
  L("sam", "ខ្ញុំមិនមែនមកលក់កិត្តិយសប្រពន្ធខ្ញុំទេ!", "I didn't come here to sell my wife's honour!", "angry",
    "steps closer", cam="mcu:sam", move={"sam": "to:40,0.1"}, pose={"sam": "fists"}),
  X("action", 2.0, "Behind his back, Hok rings a small brass bell. A thin smile.", cam="mcu:hok",
    sfx=["bell_small"]),
  L("hok", "ប៉ូលីស! ជួយផង! មានចោរចូលផ្ទះ ចង់សម្លាប់ខ្ញុំ!",
    "Police! Help! A thief has broken in — he wants to kill me!", "shout", "", cam="med:hok",
    pose={"hok": "arms_up"}, sfx=["police_whistle"]),
  X("action", 3.0, "Two policemen run in and seize Sam by the arms.", cam="wide", sfx=["footsteps_concrete"],
    move={"police": "near:sam", "police2": "to:-90,0.14"}),
  L("sam", "ខ្ញុំមិនមែនជាចោរទេ! វាទេ ដែលជាមនុស្សអាក្រក់!", "I'm not a thief! He's the evil one!",
    "desperate", "", cam="mcu:sam"),
  L("police", "ចូលផ្ទះគេពេលយប់ ហើយគំរាមម្ចាស់ផ្ទះ។ ទៅប៉ុស្តិ៍!",
    "Breaking into a house at night and threatening the owner. To the station!", "stern", "", cam="med:police"),
  X("insert", 4.0, "A colonial courtroom: a judge's high wooden bench, a ceiling fan, a gavel falls.", cam="insert:court",
    sfx=["gavel"]),
  L("narrator", "ដោយចាញ់កលថៅកែហុក សមត្រូវគេចាប់ ហើយតុលាការកាត់ទោសឲ្យជាប់គុក បីខែ។",
    "Outwitted by Boss Hok, Sam was arrested, and the court sentenced him to three months in prison.", "grave",
    "", cam="insert:court", pause=0.8),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 7 — PRISON
dict(n=10, ch=7, title_kh="គុកធំ", title_en="Prison", source="សង្ខេបរឿង ¶4-5",
     music="prison", amb="prison", loc="prison", tod="day",
     cast=["sam_prison", "chhuoy", "huor", "suos"],
     start=dict(sam_prison=(-80, 0.1, "sit_sad", 1), chhuoy=(380, 0.3, "sit", -1), huor=(-900, 0.2, "stand", 1),
                suos=(-980, 0.25, "stand", 1)),
     items=[
  X("establish", 4.5, "A high prison wall and an iron gate. A heavy door clangs shut.", cam="insert:prison_ext",
    sfx=["metal_door"]),
  X("action", 3.5, "A bare cell. A shaft of light through the bars. Sam sits on the floor, knees drawn up.",
    cam="wide", sfx=["room_tone"]),
  L("sam_prison", "សយ... អូននៅក្រៅម្នាក់ឯង... អូនស៊ីអ្វី? គេងនៅឯណា?",
    "Soy... you're out there alone... what will you eat? Where will you sleep?", "sad", "inner voice",
    cam="mcu:sam_prison"),
  X("action", 3.0, "Two older prisoners, Huor and Suos, step toward Sam. Their shadows fall over him.", cam="wide",
    move={"huor": "to:-300,0.1", "suos": "to:-380,0.18"}),
  X("insert", 3.0, "Only shadows on the wall and a scuffle of feet; Sam curls up. Cut away.", cam="insert:prison_shadow",
    sfx=["scuffle"]),
  L("narrator", "នៅក្នុងគុក សមត្រូវក្រុមអ្នកទោសចាស់ៗ ធ្វើបាបជាញឹកញាប់។",
    "In prison, Sam was often mistreated by a group of older inmates.", "grave", "",
    cam="insert:prison_shadow"),
]),
dict(n=11, ch=7, title_kh="ថ្ងៃអាទិត្យ", title_en="Visiting Day", source="សង្ខេបរឿង ¶4-5",
     music="prison", amb="prison", loc="visit", tod="day",
     cast=["sam_prison", "soy", "mom"],
     start=dict(sam_prison=(160, 0.1, "stand", -1), soy=(-140, 0.1, "stand", 1), mom=(-330, 0.2, "stand", 1)),
     items=[
  X("action", 3.0, "Sunday. The visiting room: a wooden counter and iron bars. Soy and Mom come in with a food tin.",
    cam="wide", sfx=["footsteps_concrete", "metal_door"]),
  L("soy", "បង... បងស្គមណាស់។ អូនយកបាយ និងត្រីងៀត មកឲ្យបង។",
    "You've grown so thin. I brought you rice and dried fish.", "tender, sad", "", cam="mcu:soy",
    pose={"soy": "offer"}),
  L("sam_prison", "អូនសុខសប្បាយទេ? អូនមិនគួរមកទីនេះទេ... អូនខ្មាសគេ។",
    "Are you all right? You shouldn't come here... people will look down on you.", "ashamed", "", cam="mcu:sam_prison"),
  L("soy", "ខ្មាសអ្វីបង? បងជាប្ដីរបស់អូន។ រាល់ថ្ងៃអាទិត្យ អូននឹងមកសួរបង។",
    "Why should I be ashamed? You're my husband. Every Sunday I'll come to see you.", "firm, gentle", "",
    cam="ots:sam_prison>soy"),
  L("mom", "ម៉ីផ្ញើពាក្យមកថា ពេលឯងចេញ គាត់នឹងមកទទួលឯង។",
    "Mey sends word: when you get out, he'll come to pick you up.", "kind", "", cam="med:mom"),
  X("action", 2.5, "A guard's baton raps the bars. Time is up. Soy's hand lingers on the bar.", cam="wide",
    sfx=["baton_bars"], move={"soy": "exit_left", "mom": "exit_left"}),
]),
dict(n=12, ch=7, title_kh="ពាក្យណែនាំរបស់ភូឈួយ", title_en="Phu Chhuoy's Advice", source="សង្ខេបរឿង ¶6",
     music="prison", amb="prison", loc="prison", tod="dusk",
     cast=["sam_prison", "chhuoy"],
     start=dict(sam_prison=(-60, 0.1, "sit_sad", 1), chhuoy=(200, 0.12, "sit", -1)),
     items=[
  X("action", 3.0, "Evening in the cell. The old prisoner Phu Chhuoy shifts closer to Sam.", cam="wide",
    sfx=["room_tone"]),
  L("chhuoy", "ក្មួយ... កំហឹងបាននាំក្មួយមកទីនេះ។ បើក្មួយនៅតែទុកវាក្នុងចិត្ត វានឹងនាំក្មួយទៅកន្លែងអាក្រក់ជាងនេះទៀត។",
    "Son... anger brought you here. If you keep it in your heart, it will lead you somewhere worse.", "wise",
    "", cam="med:chhuoy"),
  L("sam_prison", "ពូ... ខ្ញុំគ្រាន់តែចង់បានយុត្តិធម៌ ឲ្យប្រពន្ធខ្ញុំ។", "Uncle... I only wanted justice for my wife.",
    "bitter", "", cam="mcu:sam_prison"),
  L("chhuoy", "យុត្តិធម៌ពិត ចាប់ផ្ដើមពីការរស់នៅឲ្យត្រង់។ ចេញពីទីនេះ ទៅរកការងារសុចរិត ហើយថែប្រពន្ធក្មួយ។",
    "Real justice starts with living straight. When you leave, find honest work and look after your wife.",
    "wise, calm", "", cam="ots:sam_prison>chhuoy"),
  L("sam_prison", "បាទពូ... ខ្ញុំនឹងចាំពាក្យពូ។", "Yes, uncle... I'll remember your words.", "reflective", "",
    cam="mcu:sam_prison", pause=0.8),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 8 — A NEW CHANCE
dict(n=13, ch=8, title_kh="ឱកាសថ្មី", title_en="A New Chance", source="សង្ខេបរឿង ¶6",
     music="hope", amb="house_poor", loc="newhome", tod="day",
     cast=["sam", "soy", "mey", "yaykan"],
     start=dict(sam=(-150, 0.1, "stand", 1), soy=(-320, 0.12, "stand", 1), mey=(-520, 0.2, "stand", 1),
                yaykan=(900, 0.1, "stand", -1)),
     items=[
  X("establish", 4.0, "Morning. The prison gate opens. Sam steps into the sunlight; Soy and Mey wait beside Mey's pedicab.",
    cam="insert:prison_release", sfx=["metal_door", "birds_city"]),
  L("mey", "ឡើងជិះទៅ! ខ្ញុំរកបានផ្ទះតូចមួយឲ្យឯង ជិតវត្តមហាមន្ត្រី។",
    "Hop on! I've found you a little house near Wat Mohamontrei.", "warm, happy", "", cam="insert:prison_release"),
  X("establish", 4.5, "Mey pedals his pedicab through the morning street; Sam and Soy sit together in the seat.",
    cam="insert:pedicab_ride", sfx=["cyclo_chain", "cyclo_bell"]),
  X("action", 3.0, "A small wooden house near the temple. Grandma Kan, a kind widow, arrives pushing a cyclo.",
    cam="wide", sfx=["cyclo_chain"], move={"yaykan": "to:200,0.1"}),
  L("yaykan", "ក្មួយឈ្មោះសម មែនទេ? ម៉ីនិយាយពីក្មួយច្រើនណាស់។",
    "You must be Sam? Mey has told me so much about you.", "kind", "", cam="med:yaykan"),
  L("yaykan", "ស៊ីក្លូនេះ យាយឲ្យក្មួយយកទៅធាក់ចុះ។ ធ្វើការឲ្យត្រង់ ហើយថែប្រពន្ធឲ្យបានល្អ។",
    "Take this cyclo and ride it. Work honestly and take good care of your wife.", "kind, gentle", "",
    cam="mcu:yaykan", pose={"yaykan": "gesture_sit"}),
  L("sam", "យាយ... ខ្ញុំមិនដឹងថាត្រូវអរគុណយាយយ៉ាងម៉េចទេ។", "Grandma... I don't know how to thank you.",
    "touched, hopeful", "", cam="mcu:sam", pose={"sam": "sampeah"}),
  L("soy", "អរគុណយាយ។ យាយចិត្តល្អណាស់។", "Thank you, grandma. You're so kind.", "happy", "", cam="mcu:soy",
    pose={"soy": "sampeah"}),
  X("action", 4.0, "Sam pedals away on the cyclo, waving. Soy waves from the doorway.", cam="insert:cyclo_ride",
    sfx=["cyclo_bell", "cyclo_chain"]),
  X("insert", 2.5, "A street corner. A car swerves; brakes screech; the screen flashes white.", cam="insert:car_hit",
    sfx=["car_brake", "thud"]),
  L("narrator", "មិនយូរប៉ុន្មាន សមត្រូវឡានបុកសន្លប់ ហើយត្រូវគេដឹកទៅមន្ទីរពេទ្យព្រះកេតុមាលា។",
    "Before long, Sam was knocked unconscious by a car and taken to Preah Ket Mealea Hospital.", "grave", "",
    cam="insert:hospital_bed"),
  L("soy", "បង... បងភ្ញាក់ហើយ! អូនខ្លាចបាត់បងណាស់។", "You're awake! I was so afraid I'd lost you.",
    "cry", "", cam="insert:hospital_bed"),
  L("sam", "បងមិនអីទេ... ជីវិតយើងពិបាកមែន តែបងមិនចុះចាញ់ទេ។",
    "I'm all right... life is hard for us, but I won't give up.", "weak, determined", "",
    cam="insert:hospital_bed", pause=0.6),
]),
dict(n=14, ch=8, title_kh="រោងចក្រសាប៊ូ", title_en="The Soap Factory", source="សង្ខេបរឿង ¶7",
     music="hope", amb="factory", loc="factory", tod="day",
     cast=["sam", "worker", "worker2", "sengly", "sengan"],
     start=dict(sam=(-900, 0.1, "stand", 1), worker=(330, 0.15, "work", -1), worker2=(560, 0.4, "work", 1),
                sengly=(1000, 0.1, "stand", -1), sengan=(1080, 0.18, "stand", -1)),
     items=[
  L("narrator", "ក្រោយពីជាសះស្បើយ សមបានចូលធ្វើការ នៅរោងចក្រសាប៊ូមួយ។",
    "Once he had recovered, Sam went to work in a soap factory.", "calm", "", cam="insert:factory_ext",
    sfx=["factory_hum"]),
  X("action", 3.5, "Dawn. Sam is first through the factory door, rolling up his sleeves.", cam="wide",
    sfx=["footsteps_concrete", "factory_hum"], move={"sam": "to:-300,0.1"}),
  X("action", 3.5, "Montage: Sam carries heavy sacks of soda across the floor.", cam="wide", sfx=["sack_drop"],
    pose={"sam": "carry"}, move={"sam": "to:0,0.1"}),
  X("action", 3.0, "Montage: Sam stirs the big soap vat with a long paddle; steam rises.", cam="med:sam",
    sfx=["vat_stir"], pose={"sam": "stir"}),
  X("action", 3.0, "Montage: Sam helps a coworker carry heavy sacks to the vats.", cam="wide", sfx=["sack_drop"],
    pose={"sam": "carry", "worker": "carry"}),
  L("worker", "សម! ឯងមកមុនគេរាល់ថ្ងៃ ហើយត្រឡប់ក្រោយគេទៀត។ មិនហត់ទេឬ?",
    "Sam! You arrive before everyone and leave after everyone. Aren't you tired?", "friendly", "",
    cam="med:worker", pose={"worker": "stand"}),
  L("sam", "ហត់ក៏ហត់ដែរ។ តែការងារនេះ ឲ្យខ្ញុំមានបាយហូប ដោយមិនខ្មាសគេ។",
    "Tired, yes. But this work lets me eat without shame.", "happy", "", cam="mcu:sam", pose={"sam": "stand"}),
  X("action", 3.0, "The owner, Seng Ly, walks in with his assistant Seng An. Workers straighten up.", cam="wide",
    move={"sengly": "to:420,0.1", "sengan": "to:560,0.18"}, pose={"worker": "stand", "worker2": "stand"}),
  L("sengan", "ថៅកែ... កាប៉ូរ៉ាល់ចាស់លាឈប់ហើយ។ យើងត្រូវការអ្នកមើលការងារថ្មីម្នាក់។",
    "Boss... the old foreman has resigned. We need a new man to run the floor.", "polite", "", cam="med:sengan"),
  L("sengly", "សម។ ខ្ញុំឃើញឯងខំប្រឹងណាស់ ហើយកម្មករទាំងអស់ទុកចិត្តឯង។",
    "Sam. I've seen how hard you work, and all the workers trust you.", "calm", "", cam="med:sengly"),
  L("sengly", "ចាប់ពីថ្ងៃនេះ ឯងជាកាប៉ូរ៉ាល់។ ឯង និងប្រពន្ធ មកនៅបន្ទប់ក្នុងរោងចក្រនេះចុះ។",
    "From today you're the foreman. You and your wife may live in the room here at the factory.", "kind", "",
    cam="ots:sam>sengly"),
  L("sam", "អរគុណថៅកែ! ខ្ញុំនឹងមិនធ្វើឲ្យថៅកែខកចិត្តទេ។", "Thank you, boss! I won't let you down.",
    "happy", "", cam="mcu:sam", pose={"sam": "sampeah"}),
  X("insert", 4.0, "Evening. A small room in the factory: Soy puts a flower in a bottle on the windowsill. Sam watches, smiling.",
    cam="insert:factory_room"),
  L("soy", "បង... យើងមានបន្ទប់ជារបស់យើងហើយ។", "We have a room of our own now.", "happy", "",
    cam="insert:factory_room", pause=0.6),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 9 — WORKPLACE CONFLICT
dict(n=15, ch=9, title_kh="អ្នកគ្រប់គ្រងថ្មី", title_en="The New Manager", source="សង្ខេបរឿង ¶8-9",
     music="threat", amb="factory", loc="factory", tod="day",
     cast=["sam", "sengly", "sengan", "senghong", "worker", "worker2"],
     start=dict(sengly=(260, 0.1, "stand", -1), sengan=(420, 0.18, "stand", -1), senghong=(90, 0.14, "stand", -1),
                sam=(-200, 0.1, "stand", 1), worker=(-420, 0.2, "stand", 1), worker2=(-560, 0.35, "stand", 1)),
     items=[
  L("sengly", "សេងអាន ត្រូវទៅមើលការងារនៅហុងកុង។ ពេលខ្ញុំមិននៅ ក្មួយខ្ញុំ សេងហុង នឹងមើលរោងចក្រនេះជំនួស។",
    "Seng An must go to look after business in Hong Kong. While I'm away, my nephew Seng Hong will run the factory.",
    "official", "", cam="med:sengly"),
  L("sengan", "សម... ថែកម្មករឲ្យបានល្អណា។ ខ្ញុំនឹងត្រឡប់មកវិញឆាប់ៗ។",
    "Sam... look after the workers well. I'll be back soon.", "kind", "", cam="med:sengan"),
  X("action", 3.5, "Seng Ly and Seng An leave. Seng Hong strolls the floor, tapping a ledger with his pen.", cam="wide",
    move={"sengly": "exit_right", "sengan": "exit_right", "senghong": "to:40,0.1"}, sfx=["factory_hum"]),
  L("senghong", "ពីថ្ងៃនេះទៅ កម្មករទាំងអស់ត្រូវធ្វើការថែមពីរម៉ោង... ដោយមិនបន្ថែមប្រាក់ឈ្នួល។",
    "From today, every worker does two extra hours... with no extra pay.", "cold", "", cam="med:senghong"),
  L("senghong", "អ្នកណាឈឺ ឬមកយឺត កាត់ប្រាក់ខែចោល។ កាប៉ូរ៉ាល់ ត្រូវកត់ឈ្មោះមកឲ្យខ្ញុំ។",
    "Anyone sick or late loses his pay. The foreman will write down their names for me.", "cold", "",
    cam="mcu:senghong", pose={"senghong": "point"}),
  L("sam", "លោក... កម្មករធ្វើការហត់ណាស់ហើយ។ ខ្ញុំមិនអាចកាត់ប្រាក់ខែអ្នកឈឺបានទេ។",
    "Sir... the workers are worn out already. I can't take pay away from men who are sick.", "firm", "",
    cam="mcu:sam"),
  L("senghong", "ឯងជាអ្នកធ្វើការឲ្យខ្ញុំ មិនមែនជាមេខ្ញុំទេ។ ធ្វើតាមបញ្ជា ឬចេញទៅ!",
    "You work for me — you're not my boss. Follow orders or get out!", "harsh", "", cam="ots:sam>senghong"),
  L("sam", "បើធ្វើតាមលោក ខ្ញុំត្រូវក្បត់ចិត្តខ្លួនឯង និងក្បត់មិត្តកម្មករ។",
    "If I obey you, I betray my own conscience and my fellow workers.", "resolute", "", cam="mcu:sam"),
  L("senghong", "អញ្ចឹងចេញទៅ! ចាប់ពីថ្ងៃនេះ ឯងឈប់ធ្វើការនៅទីនេះទៀតហើយ។",
    "Then get out! As of today you no longer work here.", "angry", "", cam="med:senghong",
    pose={"senghong": "point"}),
  X("action", 4.0, "Sam unties his work apron, lays it on a crate and walks out. The workers watch in silence.",
    cam="wide", move={"sam": "exit_left"}, pose={"worker": "head_down"}),
  X("insert", 6.0, "Montage: Sam at a rice warehouse, at a sawmill, at a brick kiln — working hard; each time a gate shuts behind him.",
    cam="insert:job_montage", sfx=["gate_shut"]),
  L("narrator", "សមទៅធ្វើការកន្លែងណា ក៏គេតែងតាំងឲ្យធ្វើជាកាប៉ូរ៉ាល់ដែរ... តែមិនយូរប៉ុន្មាន ម្ចាស់កន្លែងក៏បណ្ដេញគាត់ចេញ។",
    "Wherever Sam worked, he was made foreman... but before long, the owner always sent him away.", "calm", "",
    cam="insert:job_montage", pause=0.6),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 10 — WORKERS AND POLITICAL DISAPPOINTMENT
dict(n=16, ch=10, title_kh="សមាគមកម្មករ", title_en="The Workers' Association", source="សង្ខេបរឿង ¶10",
     music="workers", amb="crowd_room", loc="hall", tod="evening",
     cast=["sam", "worker", "mey", "worker2", "worker3", "yeng"],
     start=dict(sam=(-60, 0.1, "desk", 1), worker=(220, 0.14, "sit", -1), mey=(-330, 0.2, "sit", 1),
                worker2=(430, 0.35, "sit", -1), worker3=(-520, 0.4, "sit", 1), yeng=(1000, 0.1, "stand", -1)),
     items=[
  L("narrator", "ដោយមានកម្មករស្គាល់ច្រើន សមបានរួមគ្នាបង្កើតសមាគមកម្មករមួយ។",
    "Knowing so many workers, Sam helped them found a workers' association.", "calm", "", cam="wide"),
  X("action", 3.5, "A plain wooden hall lit by a kerosene lamp. Sam writes names by hand in a membership list.",
    cam="med:sam", sfx=["pen_write", "crowd_murmur"], pose={"sam": "write"}),
  L("worker", "ប្រាក់ឈ្នួលយើងតិច ម៉ោងធ្វើការវែង។ ឈឺម្ដង ក៏បាត់ការងារ។",
    "Our pay is low and our hours are long. Fall sick once and you lose your job.", "weary", "", cam="med:worker"),
  L("sam", "យើងមិនសុំអ្វីលើសពីការពិតទេ។ យើងសុំតែការងារ ដែលឲ្យយើងរស់នៅបានដោយសេចក្ដីថ្លៃថ្នូរ។",
    "We ask for nothing beyond what is fair. Only work that lets us live with dignity.", "passionate", "",
    cam="mcu:sam", pose={"sam": "look_up"}),
  L("mey", "បើយើងនៅជាមួយគ្នា សំឡេងយើងនឹងធំជាងមុន។", "If we stand together, our voice will be louder.",
    "earnest", "", cam="med:mey"),
  X("action", 3.5, "Election season. A candidate in a pale suit, Mr. Yeng, enters. The workers turn.", cam="wide",
    move={"yeng": "to:300,0.08"}, pose={"sam": "stand"}),
  L("yeng", "បងប្អូនកម្មករ! ខ្ញុំឈ្មោះយ៉េង។ ខ្ញុំឈរឈ្មោះជាបេក្ខជនតំណាងរាស្ត្រ។",
    "Brother workers! My name is Yeng. I am standing for election to the Assembly.", "eager", "", cam="med:yeng",
    pose={"yeng": "arms_up"}),
  L("yeng", "សូមជួយខ្ញុំឲ្យជាប់ឆ្នោត។ ខ្ញុំសន្យាថា នឹងមិនភ្លេចបងប្អូនទេ។",
    "Help me win. I promise I will never forget you.", "eager", "hand on heart", cam="mcu:yeng",
    pose={"yeng": "hand_chest"}),
  L("sam", "បើលោកនិយាយពិត យើងនឹងជួយលោក។", "If you mean what you say, we will help you.", "hopeful, cautious",
    "", cam="ots:yeng>sam"),
  X("insert", 5.5, "Montage: Sam and the workers hand out plain leaflets (no text) at a modest street gathering.",
    cam="insert:campaign", sfx=["crowd_murmur"]),
  L("narrator", "សម និងកម្មករ បានដើរជួយឃោសនាឲ្យលោកយ៉េង ពេញមួយរដូវបោះឆ្នោត។",
    "Sam and the workers campaigned for Mr. Yeng all through the election season.", "calm", "",
    cam="insert:campaign"),
]),
dict(n=17, ch=10, title_kh="ក្រោយការបោះឆ្នោត", title_en="After the Election", source="សង្ខេបរឿង ¶10",
     music="neutral", amb="street", loc="office", tod="day",
     cast=["sam", "yeng", "worker"],
     start=dict(sam=(-240, 0.1, "stand", 1), worker=(-420, 0.2, "stand", 1), yeng=(900, 0.1, "stand", -1)),
     items=[
  X("action", 3.5, "Outside an office with a new brass nameplate (no text). Mr. Yeng, now elected, walks out toward his car.",
    cam="wide", move={"yeng": "to:220,0.08"}, sfx=["footsteps_concrete"]),
  L("sam", "លោកតំណាង! ខ្ញុំ សម... កាលមុនយើងជួយលោក។ ឥឡូវកម្មករយើងត្រូវការជំនួយ...",
    "Sir! It's me, Sam... we helped you before. Now our workers need help...", "hopeful", "", cam="med:sam",
    pose={"sam": "sampeah"}),
  L("yeng", "ក្រោយៗទៀតចុះ... ខ្ញុំរវល់។", "Some other time... I'm busy.", "dismissive", "doesn't stop walking",
    cam="med:yeng", move={"yeng": "exit_right"}),
  X("reaction", 3.5, "Yeng is gone; a car engine fades away. Sam is left standing on the pavement with the worker.", cam="wide",
    sfx=["car_depart"]),
  L("sam", "ពាក្យសន្យាកាលពីមុន... បាត់ទៅវិញ ដូចផ្សែង។", "All those promises... gone like smoke.", "bitter, sad",
    "", cam="mcu:sam"),
  L("sam", "ពីនេះទៅ ខ្ញុំនឹងមិនឲ្យនរណាយកខ្ញុំធ្វើជាជណ្ដើរទៀតទេ។",
    "From now on, I won't let anyone use me as a stepping-stone again.", "resolute", "", cam="cu:sam",
    pause=0.8),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 11 — FAMILY TRAGEDY
dict(n=18, ch=11, title_kh="កូនក្នុងផ្ទៃ", title_en="The Child on the Way", source="សង្ខេបរឿង ¶11",
     music="hardship", amb="night", loc="hut", tod="night",
     cast=["sam", "soy_preg"],
     start=dict(sam=(-100, 0.1, "sit", 1), soy_preg=(90, 0.1, "sit", -1)),
     items=[
  L("narrator", "មិនយូរប៉ុន្មាន សយមានផ្ទៃពោះ។ តែគ្រួសារគេ គ្មានលុយទិញថ្នាំសង្កូវ ឲ្យនាងផឹកទេ។",
    "Before long, Soy was expecting a child. But they had no money for the medicine she needed.", "calm", "",
    cam="wide"),
  L("soy_preg", "បង... កូនយើងទាត់ហើយ។", "Sam... our baby just kicked.", "happy, tender",
    "hand on her belly", cam="mcu:soy_preg", pose={"soy_preg": "hand_belly"}),
  L("sam", "កូនបងខ្លាំងដូចម្ដាយហើយ។ បងនឹងរកលុយទិញថ្នាំឲ្យអូនឲ្យបាន។",
    "Our child is strong like its mother. I'll find the money for your medicine, somehow.", "tender, determined",
    "", cam="mcu:sam"),
  L("soy_preg", "កុំបារម្ភពេកបង។ ឲ្យតែកូនយើងកើតមកសុខសប្បាយ... អូនសប្បាយចិត្តហើយ។",
    "Don't worry so much. As long as our child is born healthy... I'll be happy.", "gentle, tired", "",
    cam="two:sam,soy_preg", pause=0.6),
  X("establish", 5.0, "Night. The river. Sam poles a small boat across the dark water, a lantern at the bow; Soy lies wrapped in a krama.",
    cam="insert:river_night", sfx=["water_oar", "crickets"]),
  L("narrator", "ដល់គ្រប់ខែ សមនាំប្រពន្ធ ឆ្លងទន្លេ ទៅពឹងគ្រូពេទ្យនរា។",
    "When her time came, Sam took his wife across the river to beg Doctor Nara for help.", "grave", "",
    cam="insert:river_night"),
]),
dict(n=19, ch=11, title_kh="ទ្វារដែលបិទ", title_en="The Closed Door", source="សង្ខេបរឿង ¶11",
     music="tragedy", amb="clinic", loc="clinic", tod="night",
     cast=["sam", "nara"],
     start=dict(sam=(-700, 0.1, "stand", 1), nara=(200, 0.1, "stand", -1)),
     items=[
  X("action", 2.5, "A dim clinic corridor lit by one lantern. Sam hurries in.", cam="wide",
    move={"sam": "to:-60,0.1"}, sfx=["footsteps_wood"]),
  L("sam", "លោកគ្រូពេទ្យ! សូមជួយប្រពន្ធខ្ញុំផង! នាងឈឺពោះខ្លាំងណាស់!",
    "Doctor! Please help my wife! She's in terrible pain!", "desperate", "", cam="med:sam"),
  L("nara", "នាំនាងចូលមកក្នុងនេះ។ អ្នកចាំនៅខាងក្រៅ។", "Bring her inside. You wait out here.", "serious, urgent",
    "", cam="med:nara", move={"nara": "exit_right"}),
  X("action", 3.0, "The treatment-room door closes. Sam is alone in the corridor.", cam="wide", sfx=["door_wood"]),
  X("action", 5.0, "Time passes. The lantern burns low. Sam sits on the bench, then stands, then sits again, hands pressed together.",
    cam="wide", sfx=["room_tone"], pose={"sam": "sit_pray"}),
  X("action", 3.5, "The door opens slowly. Doctor Nara steps out and lowers his head.", cam="wide",
    sfx=["door_wood"], move={"nara": "to:200,0.1"}, pose={"sam": "stand"}),
  L("nara", "ខ្ញុំសុំទោស... ខ្ញុំបានព្យាយាមអស់ពីសមត្ថភាពហើយ។", "I'm sorry... I did everything I could.", "grave",
    "", cam="med:nara", pose={"nara": "head_down"}),
  X("reaction", 5.0, "Silence. Sam's face. No music.", cam="cu:sam", sfx=[]),
  L("sam", "សយ...", "Soy...", "broken, whisper", "", cam="cu:sam", pause=1.0),
  X("action", 4.0, "Sam sinks slowly to his knees in the lantern light.", cam="wide", pose={"sam": "kneel_grief"}),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 12 — SAM'S LOWEST POINT
dict(n=20, ch=12, title_kh="ឯកោ", title_en="Alone", source="សង្ខេបរឿង ¶12",
     music="lowest", amb="street", loc="office", tod="day",
     cast=["sam_ragged", "yeng", "guard"],
     start=dict(sam_ragged=(-200, 0.1, "stand", 1), yeng=(200, 0.1, "stand", -1), guard=(420, 0.2, "stand", -1)),
     items=[
  X("insert", 5.0, "A small temple funeral: incense smoke, a framed paper flower. Sam alone, kneeling.", cam="insert:funeral",
    sfx=["temple_bell"]),
  L("narrator", "បន្ទាប់ពីសយស្លាប់ សមត្រឡប់ទៅធាក់ស៊ីក្លូវិញ... តែជីវិតមិនប្រសើរឡើងសោះ។",
    "After Soy died, Sam went back to pedalling a cyclo... but life did not get any better.", "grave", "",
    cam="insert:funeral"),
  L("sam_ragged", "លោកយ៉េង... ខ្ញុំ សម។ ប្រពន្ធខ្ញុំទើបស្លាប់។ សូមជួយរកការងារឲ្យខ្ញុំផង។",
    "Mr. Yeng... it's me, Sam. My wife has just died. Please help me find work.", "pleading", "",
    cam="med:sam_ragged", pose={"sam_ragged": "sampeah"}),
  L("yeng", "ឯងជានរណា? ខ្ញុំមិនស្គាល់ឯងទេ។ ឆ្មាំ! នាំគាត់ចេញទៅ។",
    "Who are you? I don't know you. Guard! Show him out.", "cold, dismissive", "", cam="med:yeng"),
  X("action", 3.0, "The guard steers Sam out of the gate. The gate shuts.", cam="wide",
    move={"guard": "near:sam_ragged", "sam_ragged": "exit_left"}, sfx=["gate_shut"]),
  X("establish", 5.0, "Night rain. Sam sleeps under a shop awning on flattened cardboard. A policeman's lantern falls on him.",
    cam="insert:homeless_night", sfx=["rain_heavy"]),
  L("narrator", "សមក្លាយជាមនុស្សអនាថា គ្មានទីជម្រក គ្មានក្រដាសសម្គាល់ខ្លួន។ ប៉ូលីសចាប់ឃុំគាត់ពីរបីថ្ងៃ ទើបដោះលែង។",
    "Sam became homeless, with no shelter and no papers. The police held him for a few days before letting him go.",
    "grave", "", cam="insert:homeless_night"),
  X("establish", 4.5, "Morning market. Sam, thin and hollow-eyed, stares at steaming rice at a food stall.",
    cam="insert:market", sfx=["market_amb"]),
  L("sam_ragged", "បីថ្ងៃហើយ... គ្មានបាយមួយគ្រាប់ចូលពោះសោះ។", "Three days now... not a single grain of rice.",
    "weak", "inner voice", cam="insert:market"),
  X("insert", 4.0, "Dusk, a narrow alley. Sam crouches against a wall clutching a stolen cloth bundle, trembling.",
    cam="insert:alley", sfx=["heartbeat_soft", "dog_far"]),
  L("narrator", "ដោយការស្រេកឃ្លាន និងគ្មានទីពឹង សមបានដាច់ចិត្ត ធ្វើរឿងដែលខ្លួនធ្លាប់ស្អប់បំផុត... គឺការលួចឆក់។",
    "Starving and with nowhere to turn, Sam did the thing he had always hated most... he stole.", "grave", "",
    cam="insert:alley"),
  L("sam_ragged", "សយ... បើអូនឃើញបងពេលនេះ អូនប្រាកដជាខកចិត្តណាស់។",
    "Soy... if you could see me now, how disappointed you would be.", "ashamed, cry", "", cam="insert:alley",
    pause=0.8),
]),
# ═════════════════════════════════════════════════════════ CHAPTER 12b — RETURNING WHAT REMAINS
dict(n=21, ch=12, title_kh="ប្រគល់របស់វិញ", title_en="Returning What Remains", source="សង្ខេបរឿង ¶13",
     music="reflect", amb="night", loc="meyhome", tod="night",
     cast=["sam_ragged", "mey", "mom"],
     start=dict(sam_ragged=(-120, 0.1, "sit_sad", 1), mey=(170, 0.1, "sit", -1), mom=(380, 0.25, "stand", -1)),
     items=[
  X("action", 3.0, "Night at Mey's house. The stolen bundle lies on the mat between Sam and Mey.", cam="wide",
    sfx=["crickets"]),
  L("mey", "សម... ខ្ញុំដឹងរឿងហើយ។ ឯងមិនមែនជាមនុស្សបែបនេះទេ។",
    "Sam... I know what happened. This isn't who you are.", "serious, gentle", "", cam="med:mey"),
  L("sam_ragged", "ខ្ញុំឃ្លានពេក ម៉ី... ខ្ញុំគ្មានអ្វីនៅសល់ទៀតទេ។", "I was so hungry, Mey... I have nothing left.",
    "broken", "", cam="mcu:sam_ragged"),
  L("mey", "ភាពលំបាកបាននាំឯងមកដល់ទីនេះ។ តែឯងនៅតែអាចជ្រើសរើសថា ចង់ទៅផ្លូវណាបន្តទៀត។",
    "Hardship brought you here. But you can still choose which road you take from now on.", "wise", "",
    cam="ots:sam_ragged>mey"),
  L("mom", "សយតែងតែជឿលើចិត្តល្អរបស់ឯង។ កុំឲ្យនាងខកចិត្ត។",
    "Soy always believed in your good heart. Don't let her down.", "tender", "", cam="med:mom"),
  L("sam_ragged", "ខ្ញុំបាត់បង់ច្រើនណាស់... តែខ្ញុំមិនចង់បាត់បង់ខ្លួនឯងទៀតទេ។",
    "I've lost so much... but I don't want to lose myself as well.", "determined", "slow push-in",
    cam="cu:sam_ragged"),
  L("sam_ragged", "របស់ដែលនៅសល់ ខ្ញុំនឹងយកទៅប្រគល់ម្ចាស់វិញ។", "What's left, I'll take back to its owner.",
    "firm", "", cam="mcu:sam_ragged", pause=0.6),
]),
dict(n=22, ch=12, title_kh="ផ្ទះលោកឧកញ៉ា", title_en="The Oknha's House", source="សង្ខេបរឿង ¶13",
     music="confront", amb="house", loc="mansion", tod="day",
     cast=["sam_ragged", "oknha", "police"],
     start=dict(sam_ragged=(-220, 0.1, "stand", 1), oknha=(160, 0.1, "stand", -1), police=(-1000, 0.14, "stand", 1)),
     items=[
  X("action", 3.0, "A grand hall with carved wood and a gilded cabinet. Sam kneels and sets the bundle on the floor.",
    cam="wide", pose={"sam_ragged": "kneel"}, sfx=["cloth_rustle"]),
  L("sam_ragged", "លោកឧកញ៉ា... ខ្ញុំយករបស់លោកមកប្រគល់វិញ។ ខ្ញុំខុសហើយ។ សូមលោកអភ័យទោសឲ្យខ្ញុំផង។",
    "Your Excellency... I've brought your things back. I was wrong. Please forgive me.", "ashamed", "",
    cam="med:sam_ragged", pose={"sam_ragged": "kneel_sampeah"}),
  L("oknha", "ចោរ នៅតែជាចោរ! ប៉ូលីស! ចាប់វាទៅ!", "A thief is still a thief! Police! Take him away!", "harsh",
    "", cam="med:oknha", pose={"oknha": "point"}),
  X("action", 2.5, "A policeman strides in and takes Sam by the arm.", cam="wide", move={"police": "near:sam_ragged"},
    sfx=["footsteps_concrete"], pose={"sam_ragged": "stand"}),
  L("police", "ឯងត្រូវទៅតាមយើង។", "You're coming with us.", "stern", "", cam="med:police"),
  L("narrator", "ទោះសមយករបស់មកប្រគល់វិញក៏ដោយ លោកឧកញ៉ាមិនព្រមអភ័យទោសទេ។ សមត្រូវជាប់គុក ប្រាំមួយខែ។",
    "Even though Sam returned what he had taken, the Oknha would not forgive him. Sam was jailed for six months.",
    "grave", "", cam="insert:prison_window"),
  L("sam_ragged", "លើកនេះ ខ្ញុំទទួលទោសដោយស្ងប់ចិត្ត។ ខ្ញុំខុសពិតមែន។",
    "This time I accept my punishment with a quiet heart. I really was wrong.", "calm, accepting", "inner voice",
    cam="insert:prison_window", pause=0.6),
]),
# ═════════════════════════════════════════════════════════ ENDING — THE YOUNG MINISTER / NEW SUN
dict(n=23, ch=12, title_kh="លោករដ្ឋមន្ត្រីវ័យក្មេង", title_en="The Young Minister", source="សង្ខេបរឿង ¶14",
     music="hope", amb="hospital", loc="ward", tod="day",
     cast=["sam", "minister"],
     start=dict(sam=(-80, 0.1, "bed", 1), minister=(170, 0.1, "stand", -1)),
     items=[
  X("insert", 2.5, "Released. Sam crosses a road; a black car brakes too late; a white flash.", cam="insert:car_hit2",
    sfx=["car_brake", "thud"]),
  X("action", 3.0, "A hospital ward. Sam wakes in bed. A young man in a pale suit stands beside him: the minister.",
    cam="wide", sfx=["room_tone"]),
  L("minister", "ខ្ញុំសុំទោស។ អ្នកបើកឡានខ្ញុំ មិនបានប្រយ័ត្ន។ នេះប្រាក់ប្រាំរយរៀល ទុកព្យាបាលខ្លួន។",
    "I'm sorry. My driver wasn't careful. Here are five hundred riels for your treatment.", "kind", "",
    cam="med:minister", pose={"minister": "offer_money"}),
  L("sam", "អរគុណលោក... តែខ្ញុំមិនយកលុយទេ។ បើលោកចង់ជួយខ្ញុំមែន សូមជួយរកការងារឲ្យខ្ញុំធ្វើ។",
    "Thank you, sir... but I won't take the money. If you really want to help me, please help me find work.",
    "earnest, dignified", "", cam="mcu:sam"),
  L("minister", "អ្នកផ្សេង ចង់បានតែលុយ... ឯងជាមនុស្សចម្លែកណាស់។", "Others only want money... you're an unusual man.",
    "thoughtful", "", cam="mcu:minister"),
  L("minister", "បើអញ្ចឹង មកនៅថែផ្ទះខ្ញុំចុះ។ ខ្ញុំត្រូវការមនុស្សស្មោះត្រង់ម្នាក់។",
    "Then come and look after my house. I need an honest man.", "warm", "", cam="two:sam,minister"),
  X("insert", 4.5, "A quiet garden. Sam waters plants in the morning light; he pauses and almost smiles.", cam="insert:garden",
    sfx=["birds_city", "water_pour"]),
  L("narrator", "ចាប់ពីពេលនោះមក សមបានរស់នៅដោយសុខកាយ សប្បាយចិត្ត ដោយការងារដ៏សុចរិត។",
    "From then on, Sam lived in health and peace of mind, through honest work.", "calm", "",
    cam="insert:garden", pause=0.6),
]),
dict(n=24, ch=12, title_kh="ព្រះអាទិត្យថ្មី", title_en="A New Sun", source="សង្ខេបរឿង ¶15",
     music="sunrise", amb="country", loc="village", tod="dawn",
     cast=["sam"],
     start=dict(sam=(0, 0.1, "stand", 1)),
     items=[
  L("narrator", "ពេលស្រុកទេសមានសន្តិភាព សមបានវិលត្រឡប់ទៅស្រុកកំណើតវិញ ដើម្បីធ្វើជាកសិករ ដូចកាលពីដើម។",
    "When peace came to the country, Sam went back to his home village to be a farmer, as he once was.",
    "calm", "", cam="insert:final_sunrise"),
  X("establish", 7.0, "Before dawn, the dark sky over the old fields slowly brightens. Sam stands at the field's edge with a hoe.",
    cam="insert:final_sunrise", sfx=["birds_morning"]),
  L("sam", "សយ... បងត្រឡប់មកផ្ទះវិញហើយ។ លើដីចាស់នេះ... ព្រះអាទិត្យថ្មីកំពុងរះ។",
    "Soy... I've come home. Over this old land... a new sun is rising.", "reflective, hopeful", "",
    cam="insert:final_sunrise"),
  L("narrator", "ជីវិតអ្នកក្រ ពោរពេញដោយការលំបាក... តែការងារស្មោះត្រង់ និងសេចក្ដីថ្លៃថ្នូរ នៅតែជាពន្លឺ ដែលនាំផ្លូវទៅកាន់ថ្ងៃថ្មី។",
    "The lives of the poor are full of hardship... but honest work and dignity remain a light that leads toward a new day.",
    "calm, warm", "", cam="insert:final_sunrise", pause=1.0),
  X("ending", 8.0, "Sunrise fills the frame. A subtle title: ព្រះអាទិត្យថ្មីរះលើផែនដីចាស់.", cam="insert:title_end"),
]),
]

# costume variants share one voice with the base character
VOICE_OF = {"soy_preg": "soy", "sam_ragged": "sam", "sam_prison": "sam"}
CHARACTERS["soy_preg"] = dict(kh="សយ", en="Soy")
CHARACTERS["sam_ragged"] = dict(kh="សម", en="Sam")
CHARACTERS["sam_prison"] = dict(kh="សម", en="Sam")

def voice_of(sp):
    return VOICE_OF.get(sp, sp)


def all_lines():
    out = []
    for s in SCENES:
        for it in s["items"]:
            if it["type"] == "line":
                out.append((s["n"], it))
    return out


if __name__ == "__main__":
    ls = all_lines()
    chars = sum(len(it["tts"]) for _, it in ls)
    print(len(ls), "lines,", chars, "Khmer characters")
    from collections import Counter
    print(Counter(voice_of(it["sp"]) for _, it in ls))
    shots = sum(1 for s in SCENES for it in s["items"] if it["type"] == "shot")
    sdur = sum(it["dur"] for s in SCENES for it in s["items"] if it["type"] == "shot")
    print(shots, "action shots,", round(sdur), "s")
